//resets
export const RESET_ERROR = "RESET_ERROR";
export const RESET_USER = "RESET_USER";
export const RESET_CHARACTER = "RESET_CHARACTER";
export const RESET_REDIRECT = "RESET_REDIRECT";

//sign up
export const SIGN_UP_PENDING = "SIGN_UP_PENDING";
export const SIGN_UP_FULFILLED = "SIGN_UP_FULFILLED";
export const SIGN_UP_REJECTED = "SIGN_UP_REJECTED";

//login
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_FULFILLED = "LOGIN_FULFILLED";
export const LOGIN_REJECTED = "LOGIN_REJECTED";

//get user info
export const GET_USER_PENDING = "GET_USER_PENDING";
export const GET_USER_FULFILLED = "GET_USER_FULFILLED";
export const GET_USER_REJECTED = "GET_USER_REJECTED";

//character wizard - sync
export const SAVE_COLOR = "SAVE_COLOR";
export const SAVE_RACE = "SAVE_RACE";
export const SAVE_ARCHETYPE = "SAVE_ARCHETYPE";
export const SAVE_FEAR = "SAVE_FEAR";
export const SAVE_PET = "SAVE_PET";
export const SAVE_FAMILY = "SAVE_FAMILY";

//character wizard - async
export const SUBMIT_CHARACTER_PENDING = "SUBMIT_CHARACTER_PENDING";
export const SUBMIT_CHARACTER_FULFILLED = "SUBMIT_CHARACTER_FULFILLED";
export const SUBMIT_CHARACTER_REJECTED = "SUBMIT_CHARACTER_REJECTED";

//dashboard - sync
export const GET_ALL_CHARS_PENDING = "GET_ALL_CHARS_PENDING";
export const GET_ALL_CHARS_FULFILLED = "GET_ALL_CHARS_FULFILLED";
export const GET_ALL_CHARS_REJECTED = "GET_ALL_CHARS_REJECTED";
